spring:
  datasource:
    url: jdbc:postgresql://chaindonate-db:5432/chaindonate
    username: chaindonate
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: chaindonate-backend

server:
  port: 8080
